name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Create cicd directory
        run: mkdir -p cicd  # Ensure the cicd directory exists

      - name: Decode Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > cicd/ibkart.jks  # Restore the keystore in the cicd directory

      - name: Build with Gradle
        run: |
          ./gradlew bundleRelease \
          -Pandroid.injected.signing.store.file=$(pwd)/cicd/ibkart.jks \
          -Pandroid.injected.signing.store.password=ibkart@msspay \
          -Pandroid.injected.signing.key.alias=ibkart \
          -Pandroid.injected.signing.key.alias.password=ibkart@msspay

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CiCd.aab
          path: app/build/outputs/bundle/release/app-release.aab

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: in.ibkart.agent
          releaseFiles: app/build/outputs/bundle/release/app-release.aab
          track: internal
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew
          mappingFile: app/build/outputs/mapping/release/mapping.txt
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib
