name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'adopt'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Build with Gradle
        run: ./gradlew assembleRelease

      - name: List Output Directory
        run: ls -R app/build/outputs

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CiCd.aab
          path: app/release/app-release.aab  # Adjust for release AAB

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: in.ibkart.agent
          releaseFiles: app/release/app-release.aab  # Correct path for the release AAB
          track: internal
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew  # Ensure this directory exists or remove this line
          mappingFile: app/build/outputs/mapping/release/mapping.txt  # Adjust if needed
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib  # Adjust if needed
