name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Setup Keystore
        run: |
          mkdir -p app/keystore
          echo "${{ secrets.KEYSTORE_CONTENT }}" | base64 --decode > app/keystore/ibkart.jks

      - name: Clean Build
        run: ./gradlew clean

      - name: Increment Version Code
        run: |
          currentVersionCode=$(grep 'versionCode' app/build.gradle.kts | grep -o '[0-9]*')
          newVersionCode=$((currentVersionCode + 1))
          sed -i "s/versionCode = $currentVersionCode/versionCode = $newVersionCode/" app/build.gradle.kts
          newVersionName="V1.0.$newVersionCode"
          sed -i "s/versionName = \".*\"/versionName = \"$newVersionName\"/" app/build.gradle.kts

      - name: Build with Gradle
        run: ./gradlew bundleRelease

      - name: Move AAB to Desired Path
        run: |
          mkdir -p app/release
          mv app/build/outputs/bundle/release/app-release.aab app/release/test.aab || echo "AAB file not found"

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab
          if-no-files-found: warn

  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Download Build Artifact
        uses: actions/download-artifact@v3
        with:
          name: app-bundle
          path: app/build/outputs/bundle/release/app-release.aab

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}
          packageName: in.ibkart.agent
          releaseFiles: ${{ github.workspace }}/app/release/test.aab
          track: internal
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
