name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'  # Using Temurin for JDK

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew  # Ensure the Gradle wrapper is executable

      - name: Copy Keystore File
        run: |
          echo "${{ secrets.KEYSTORE_CONTENT }}" > ibkart.jks  # Restore the keystore from a secret

      - name: Build with Gradle
        run: ./gradlew bundleRelease -Pandroid.injected.signing.store.file=ibkart.jks \
          -Pandroid.injected.signing.store.password=${{ secrets.KEYSTORE_PASSWORD }} \
          -Pandroid.injected.signing.key.alias=${{ secrets.KEY_ALIAS }} \
          -Pandroid.injected.signing.key.alias.password=${{ secrets.KEY_ALIAS_PASSWORD }}  # Pass the signing config

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CiCd.aab
          path: app/build/outputs/bundle/release/app-release.aab  # Path for the AAB

  upload:
    runs-on: ubuntu-latest
    needs: build  # Ensure the build job completes before uploading

    steps:
      - name: Setup repo
        uses: actions/checkout@v4

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}  # Updated secret name
          packageName: in.ibkart.agent  # Updated package name
          releaseFiles: app/build/outputs/bundle/release/app-release.aab  # Correct path for the AAB
          track: internal  # Set to internal for internal testing
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew  # Path for what's new notes
          mappingFile: app/build/outputs/mapping/release/mapping.txt  # Path for ProGuard mapping file
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib  # Path for debug symbols
