name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'  # Using Temurin for JDK

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew  # Ensure the Gradle wrapper is executable

      - name: Build with Gradle
        run: ./gradlew build

      - name: Upload a Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CiCd.apk
          path: app/build/outputs/apk/debug/app-debug.apk
