name: AndroidBuild

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4.4.0
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission to gradlew
        run: chmod +x ./gradlew

      - name: Create Keystore
        run: echo "${{ secrets.KEYSTORE_CONTENT }}" > ibkart_cicd.jks
        env:
          KEYSTORE_CONTENT: ${{ secrets.KEYSTORE_CONTENT }}  # Store your keystore content as a secret

      - name: Build with Gradle
        run: ./gradlew bundleRelease  # Build the release version AAB

      - name: Upload Build Artifact
        uses: actions/upload-artifact@v3
        with:
          name: CiCd.aab
          path: app/build/outputs/bundle/release/app-release.aab  # Path for the AAB

  upload:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Upload to Play Store
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_JSON }}  # Your Play Store JSON secret
          packageName: in.ibkart.agent  # Your app's package name
          releaseFiles: app/build/outputs/bundle/release/app-release.aab  # Correct path for the AAB
          track: internal  # Use internal track for testing
          status: inProgress
          inAppUpdatePriority: 2
          userFraction: 0.33
          whatsNewDirectory: distribution/whatsnew  # Path for what's new notes
          mappingFile: app/build/outputs/mapping/release/mapping.txt  # Path for ProGuard mapping file
          debugSymbols: app/intermediates/merged_native_libs/release/out/lib  # Path for debug symbols

      - name: Cleanup Keystore
        run: rm ibkart_cicd.jks  # Clean up the keystore file after the build
